version: "3.5"
services:
  notebooks:
    container_name: unlearning-notebooks-PEM-text
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["poetry", "run", "jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=20e10069-1b7c-403f-9895-f6650f4e90d9"]
    volumes:
      - ./:/src
      - ../libs:/libs
    environment:
      - PYTHONPATH=.:/src:/libs:/
    ports:
       - 8888:8888
    env_file:
      - .env
